name: jenkins-dockercompose

services:
  jenkins:
    environment:
      JENKINS_OPTS: --httpPort=8080
    image: jenkins/jenkins:2.472-alpine-jdk21
    networks:
      default: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8080
        published: "8080"
        protocol: tcp
      - mode: ingress
        host_ip: 127.0.0.1
        target: 50000
        published: "50000"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: jenkins_data
        target: /var/jenkins_home
        volume: {}
networks:
  default:
    name: jenkins
    external: true
volumes:
  jenkins_data:
    name: jenkins-dockercompose_jenkins_data
    driver: local
