name: jenkins/jenkins

services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    restart: always
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:50000:50000'
    volumes:
      - 'jenkins_data:/var/jenkins_home'

      
volumes:
  jenkins_data:
    driver: local

networks:
  default:
    external:
      name: jenkins  # Use the existing network
