name: jenkins/jenkins

services:
  jenkins:
    image: 'jenkins/jenkins:lts'  # Using the LTS version is recommended for stability
    restart: always
    ports:
      - '127.0.0.1:8080:8080'  # Binding Jenkins HTTP port to localhost
      - '127.0.0.1:50000:50000'  # Binding Jenkins agent port to localhost
      # - '127.0.0.1:8443:8443'  # Uncomment if using HTTPS
    volumes:
      - 'jenkins_data:/var/jenkins_home'  # Persistent storage for Jenkins data
    environment:
      - 'JENKINS_OPTS=--httpPort=8080'  # Set HTTP port, HTTPS can be configured if needed
      # - 'JENKINS_OPTS=--httpPort=8080 --httpsPort=8443'  # Uncomment to enable HTTPS with proper configuration

volumes:
  jenkins_data:
    driver: local

networks:
  default:
    external:
      name: jenkins  # Using an existing external network named 'jenkins'
